# services:
#   database:
#     image: postgres:17
#     container_name: company_db
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: company_db
#     ports:
#       - "5440:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
services:
  database:
    image: postgres:17
    container_name: company_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: company_db
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/backup_db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: